### PR TITLE
Upgrade pip before installing packages

### PR DESCRIPTION
**Pull request by yuvipanda**
We tried to upgrade just jupyterhub and nbgitpuller package, but this seems to be causing it to refuse to start:

```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 5, in <module>
    from jupyterhub.singleuser import main
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/singleuser/__init__.py", line 5, in <module>
    from .app import SingleUserNotebookApp, main
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/singleuser/app.py", line 15, in <module>
    from .mixins import make_singleuser_app
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/singleuser/mixins.py", line 44, in <module>
    from ..log import log_request
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/log.py", line 14, in <module>
    from .handlers.pages import HealthCheckHandler
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/handlers/__init__.py", line 1, in <module>
    from . import base, login, metrics, pages
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 24, in <module>
    from .. import __version__, orm, roles, scopes
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/orm.py", line 31, in <module>
    from sqlalchemy.orm import (
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/__init__.py", line 56, in <module>
    from .decl_api import add_mapped_attribute as add_mapped_attribute
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/decl_api.py", line 164, in <module>
    query_expression,
TypeError: dataclass_transform() got an unexpected keyword argument
'field_specifiers'
```

Googling around, this looks like a version mismatch mostl likely, caused by https://github.com/2i2c-org/2i2c-hubs-image/pull/4. It pinned 'top level' packages but nothing more basic, so most likely a dependent package (perhaps sqlalchemy) got fucked up.

Hopefully, newer version of pip will actually SAT solve a little and get us better versions. Let's see.

### CODE REVIEW

File: requirements.txt [hunk 1]
```diff
@@ -16,7 +16,7 @@ altair==4.2.0
 astroquery==0.4.6
 astropy==4.3.1
 galpy==1.7.2
-catalystcoop.pudl==0.3.2
+catalystcoop.pudl
 dask==2020.12.0
 distributed==2020.12.0
 dask-gateway==0.9.0
```
Comment (consideRatio) [inline requirements.txt:22]: We have pins to ancient versions of distributed and such =/

Comment (yuvipanda) [reply requirements.txt:22]: @consideRatio indeed, almost all these versions are ancient! see https://github.com/2i2c-org/2i2c-hubs-image/pull/4.

This repo needs a lot of TLC

Comment (consideRatio) [reply requirements.txt:22]: I'd like to propose staying away from conda, and adopting the strategies used by z2jh and binderhub etc where requirements.in + requirements.txt is version controlled, and re-freezes are automated by github actions that can be triggered manually or scheduled.

Comment (yuvipanda) [reply requirements.txt:22]: Basically the current setup is untenable, and anything is better than what we have :) I'd actually love to propose retiring this image entirely, and setting up our default to either something from jupyter docker-stacks or pangeo image instead! I do think that for *user images* the community has sort of settled on conda, and I have given up trying to push for freezing purley from pip there - especially after anything touching gdal.

Anyway, I think there are two outcomes here:

1. What to do with *this* repo
2. What to suggest for users who are maintaining their own images

I think for (1) i'd suggest we get rid of it, and move to using the *pangeo images* as default. However, it would need to probably happen during a semester break or something.

Comment (yuvipanda) [reply requirements.txt:22]: Trying to get https://pypi.org/project/shapely/ or https://pypi.org/project/websockify/ working was what made me give up on using *purely pip* for user images. The former breaks in funky ways if you try to use it with other packages that use gdal, and the latter installs but doesn't work :D

Comment (damianavila) [reply requirements.txt:22]: I totally concur with the idea to consume some upstream image as our default image.
